// Code generated by "stringer -type T t.go"; DO NOT EDIT.

package statetype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Rolling-0]
	_ = x[DiscardingResources-1]
	_ = x[MovingRobber-2]
	_ = x[RobbingNeighboringCommunity-3]
	_ = x[NormalGameplay-4]
}

const _T_name = "RollingDiscardingResourcesMovingRobberRobbingNeighboringCommunityNormalGameplay"

var _T_index = [...]uint8{0, 7, 26, 38, 65, 79}

func (i T) String() string {
	if i < 0 || i >= T(len(_T_index)-1) {
		return "T(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _T_name[_T_index[i]:_T_index[i+1]]
}
