// Code generated by "stringer -type T t.go"; DO NOT EDIT.

package eventtype

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RolledNumber-0]
	_ = x[EndedTurn-1]
	_ = x[ResourcesDiscarded-2]
	_ = x[PlacedRobber-3]
	_ = x[RobbedNeighboringCommunity-4]
	_ = x[BuiltRoad-5]
	_ = x[BuiltSettlement-6]
	_ = x[BuiltCity-7]
	_ = x[AcceptedTrade-8]
	_ = x[OfferedTrade-9]
	_ = x[PerformedMaritimeTrade-10]
	_ = x[PurchasedDevelopmentCard-11]
	_ = x[PlayedMonopolyCard-12]
	_ = x[PlayedMonumentCard-13]
	_ = x[PlayedSoldierCard-14]
	_ = x[PlayedYearOfPlentyCard-15]
}

const _T_name = "RolledNumberEndedTurnResourcesDiscardedPlacedRobberRobbedNeighboringCommunityBuiltRoadBuiltSettlementBuiltCityAcceptedTradeOfferedTradePerformedMaritimeTradePurchasedDevelopmentCardPlayedMonopolyCardPlayedMonumentCardPlayedSoldierCardPlayedYearOfPlentyCard"

var _T_index = [...]uint16{0, 12, 21, 39, 51, 77, 86, 101, 110, 123, 135, 157, 181, 199, 217, 234, 256}

func (i T) String() string {
	if i < 0 || i >= T(len(_T_index)-1) {
		return "T(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _T_name[_T_index[i]:_T_index[i+1]]
}
