// Code generated by "stringer -type Color color.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-0]
	_ = x[Orange-1]
	_ = x[Yellow-2]
	_ = x[Green-3]
	_ = x[Blue-4]
	_ = x[Purple-5]
	_ = x[Puce-6]
	_ = x[Brown-7]
	_ = x[White-8]
}

const _Color_name = "RedOrangeYellowGreenBluePurplePuceBrownWhite"

var _Color_index = [...]uint8{0, 3, 9, 15, 20, 24, 30, 34, 39, 44}

func (i Color) String() string {
	if i < 0 || i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
